sudo: required
language: generic 
services:
  - docker

before_install:
  #-t jjacckk/react-test = Alias para la imagen que se crea para facilitar su uso en comandos posteriores
  - docker build -t jjacckk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jjacckk/react-test npm run test

after_success:
  - docker build -t jjacckk/multi-client ./client
  - docker build -t jjacckk/multi-nginx ./nginx
  - docker build -t jjacckk/multi-server ./server
  - docker build -t jjacckk/multi-worker ./worker
  # Login to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push jjacckk/multi-client
  - docker push jjacckk/multi-nginx
  - docker push jjacckk/multi-server
  - docker push jjacckk/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-886536634566'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY